NumPy is a general-purpose array-processing package. 
It provides a high-performance multidimensional array object, and tools for working with these arrays. 
It is the fundamental package for scientific computing with Python

In [3]:
import numpy as np

## What is an array
- An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [4]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape #to check the dimensionality

(5,)

In [10]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

mdarr = np.array([my_lst1,my_lst2,my_lst3])

In [12]:
mdarr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

- This is a 2D array: Way to recognise a 2D array is, it starts with 2 brackets: like array([[, and ends with2 brackets, like ]]).

In [13]:
print(mdarr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [14]:
mdarr.shape

(3, 5)

In [15]:
# reshaping:

mdarr.reshape(5,3) #make sure number of elements remain same

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [16]:
#eg of diff size
mdarr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [17]:
#SAME SIZE
mdarr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])